# GoPine System Configuration Schema
---
# Server Configuration
server:
  # Server network settings
  network:
    host: 0.0.0.0
    port: 8080
    websocket_port: 8081
    # SSL/TLS configuration
    ssl:
      enabled: true
      cert_file: /path/to/cert.pem
      key_file: /path/to/key.pem
  
  # Database connection settings
  database:
    type: postgresql
    host: localhost
    port: 5432
    username: gopine
    password: ${DB_PASSWORD}  # Environment variable reference
    database_name: gopine
    ssl_mode: require
    connection_pool_size: 10
  
  # Job queue settings
  job_queue:
    max_queue_size: 1000
    priority_levels: 10
    default_priority: 5
    job_retention_days: 30
    completed_job_retention_days: 7
  
  # Node management settings
  node_management:
    heartbeat_interval_seconds: 60
    node_timeout_seconds: 180
    auto_reassign_jobs: true
    reassign_after_seconds: 300
    max_retries: 3
  
  # Authentication and security
  auth:
    jwt_secret: ${JWT_SECRET}  # Environment variable reference
    token_expiry_hours: 24
    allow_anonymous_job_submission: false
    ip_whitelist:
      - 192.168.1.0/24
      - 10.0.0.0/8

# Node Agent Configuration
node_agent:
  # Connection settings
  connection:
    server_url: https://gopine-server.example.org:8080
    websocket_url: wss://gopine-server.example.org:8081
    reconnect_interval_seconds: 30
    max_reconnect_attempts: 10
  
  # Resource management
  resources:
    max_cpu_percent: 80
    max_memory_percent: 70
    min_free_disk_space_mb: 1000
    concurrent_jobs: 2
  
  # Job processing
  job_processing:
    # Work directory for temporary files
    work_dir: /tmp/gopine
    cleanup_after_job: true
    timeout_safety_margin_seconds: 60
  
  # Scheduling
  scheduling:
    working_hours_only: true
    working_hours:
      start: "18:00"
      end: "08:00"
    working_days:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
  
  # Logging
  logging:
    level: info
    file: /var/log/gopine-agent.log
    max_size_mb: 10
    max_files: 5

# Job Types Configuration
job_types:
  ocr:
    enabled: true
    max_file_size_mb: 50
    supported_input_formats:
      - png
      - jpg
      - jpeg
      - pdf
      - tiff
    engines:
      - tesseract
      - google
    default_engine: tesseract
    tesseract_path: /usr/bin/tesseract
    default_languages:
      - eng
  
  pdf_parse:
    enabled: true
    max_file_size_mb: 100
    max_pages: 500
    extraction_timeout_seconds: 1800
    supported_extraction_tasks:
      - text
      - tables
      - forms
      - images
      - metadata
    default_tasks:
      - text
      - metadata

# System-wide Settings
system:
  # Feature flags
  features:
    enable_dashboard: true
    enable_notifications: true
    enable_auto_updates: true
  
  # File storage (LAN environment only)
  file_storage:
    type: local
    local_path: /var/gopine/files
    retention_days: 30
    network_share_path: \\fileserver\gopine-files
    smb_credentials:
      username: ${SMB_USERNAME}
      password: ${SMB_PASSWORD}
      domain: WORKGROUP
  
  # Email notifications
  notifications:
    smtp:
      server: smtp.example.org
      port: 587
      username: notifications@example.org
      password: ${SMTP_PASSWORD}
      from_address: gopine@example.org
    notification_events:
      job_completion: true
      system_errors: true
      node_offline: true
  
  # Monitoring
  monitoring:
    enable_prometheus: true
    prometheus_port: 9090
    health_check_interval_seconds: 60
    alert_thresholds:
      queue_size_warning: 500
      queue_size_critical: 900
      job_processing_time_warning_seconds: 1800
      node_count_minimum: 3